Map photographerData = {
  "data": [
    {
  "photographerId": "1",
  "photographerTitle": "عبدالسلام محمد (abdo_elkhwaga)",
  "photographerAddress": "No Address",
  "photographerPhone1": "No Phone",
  "photographerPhone2": "No Phone",
  "photographerPhone3": "No Phone",
  "photographerFacebook": "No Facebook",
  "photographerWhatsApp": "No WhatsApp",
  "photographerDescription": "افضل قاعات الافراح في مصر",
  "photographerPrice": "0.0",
  "photographerLocation": "Other",
  "photographerCategory": "photographer",
  "photographerRating": "5.0",
  "photographerCreated": DateTime.now(),
  "lastUpdate": DateTime.now(),
  "photographerImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer1_1.png?alt=media&token=d8777f02-87d0-47d3-ab71-8b254bc4fd77", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer1_2.png?alt=media&token=f305bc9c-4cc9-4f11-a334-c13121423853", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer1_3.png?alt=media&token=9fd75a66-feb1-43f0-9491-1f332b238d0b", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer1_4.png?alt=media&token=c26cd5cd-4c7f-4bbc-9c42-7bf2245db01f"]
    },
    {
  "photographerId": "2",
  "photographerTitle": "عبدلله صدقي (Abdullah Sidky photographer)",
  "photographerAddress": "No Address",
  "photographerPhone1": "No Phone",
  "photographerPhone2": "No Phone",
  "photographerPhone3": "No Phone",
  "photographerFacebook": "No Facebook",
  "photographerWhatsApp": "No WhatsApp",
  "photographerDescription": "افضل قاعات الافراح في مصر",
  "photographerPrice": "0.0",
  "photographerLocation": "Other",
  "photographerCategory": "photographer",
  "photographerRating": "5.0",
  "photographerCreated": DateTime.now(),
  "lastUpdate": DateTime.now(),
  "photographerImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer2_1.png?alt=media&token=a00a2e30-456c-4814-83a4-84816f6c6d95", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer2_2.png?alt=media&token=6fee2a4f-68d6-48e6-9192-14c6d4ee6a92", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer2_3.png?alt=media&token=c840f7e1-a5b9-478e-92ed-98714188d790", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer2_4.png?alt=media&token=c5a36274-16e0-425e-b460-579c00ae980e"]
    },
    {
  "photographerId": "3",
  "photographerTitle": "هبه ابراهيم (H Graphii)",
  "photographerAddress": "No Address",
  "photographerPhone1": "No Phone",
  "photographerPhone2": "No Phone",
  "photographerPhone3": "No Phone",
  "photographerFacebook": "No Facebook",
  "photographerWhatsApp": "No WhatsApp",
  "photographerDescription": "افضل قاعات الافراح في مصر",
  "photographerPrice": "0.0",
  "photographerLocation": "Other",
  "photographerCategory": "photographer",
  "photographerRating": "5.0",
  "photographerCreated": DateTime.now(),
  "lastUpdate": DateTime.now(),
  "photographerImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer3_1.png?alt=media&token=61589112-0b5c-4601-8386-d58534b41c7a", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer3_2.png?alt=media&token=7dd16e79-1f30-42f1-92ca-912053ef7be8", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer3_3.png?alt=media&token=b75130b7-8e4e-4de8-9ef0-8714f83451b4", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer3_4.png?alt=media&token=5b244644-22f0-4760-87f8-b6f6a3c55a43"]
    },
    {
  "photographerId": "4",
  "photographerTitle": "مصطفي بدر ( mostafabadr_photography)",
  "photographerAddress": "No Address",
  "photographerPhone1": "No Phone",
  "photographerPhone2": "No Phone",
  "photographerPhone3": "No Phone",
  "photographerFacebook": "No Facebook",
  "photographerWhatsApp": "No WhatsApp",
  "photographerDescription": "افضل قاعات الافراح في مصر",
  "photographerPrice": "0.0",
  "photographerLocation": "Other",
  "photographerCategory": "photographer",
  "photographerRating": "5.0",
  "photographerCreated": DateTime.now(),
  "lastUpdate": DateTime.now(),
  "photographerImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer4_1.png?alt=media&token=7122806e-7851-41dd-bd04-37da2ee776f0", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer4_2.png?alt=media&token=6259553f-325e-4455-913d-7fecc50c6126", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer4_3.png?alt=media&token=a3778b49-f33a-41d0-be68-50bdffddd10b", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer4_4.png?alt=media&token=4a63acb4-1e97-4151-80ba-0788cc5ab465"]
    },
    {
  "photographerId": "5",
  "photographerTitle": "احمد الصغير ( Ahmed Elsugheir)",
  "photographerAddress": "No Address",
  "photographerPhone1": "No Phone",
  "photographerPhone2": "No Phone",
  "photographerPhone3": "No Phone",
  "photographerFacebook": "No Facebook",
  "photographerWhatsApp": "No WhatsApp",
  "photographerDescription": "افضل قاعات الافراح في مصر",
  "photographerPrice": "0.0",
  "photographerLocation": "Other",
  "photographerCategory": "photographer",
  "photographerRating": "5.0",
  "photographerCreated": DateTime.now(),
  "lastUpdate": DateTime.now(),
  "photographerImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer5_1.png?alt=media&token=360a131a-41ef-47ae-8c8a-8c9795b91874", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer5_2.png?alt=media&token=b42fcf44-843d-4589-99d0-89514e967865", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer5_3.png?alt=media&token=68d4da21-b2c1-48a1-b42b-c0d7e405df1d", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer5_4.png?alt=media&token=f5c6d45d-9f03-4de7-bf55-781363640d36"]
    },
    {
  "photographerId": "6",
  "photographerTitle": "العطار ( Elattar Photography)",
  "photographerAddress": "No Address",
  "photographerPhone1": "No Phone",
  "photographerPhone2": "No Phone",
  "photographerPhone3": "No Phone",
  "photographerFacebook": "No Facebook",
  "photographerWhatsApp": "No WhatsApp",
  "photographerDescription": "افضل قاعات الافراح في مصر",
  "photographerPrice": "0.0",
  "photographerLocation": "Other",
  "photographerCategory": "photographer",
  "photographerRating": "5.0",
  "photographerCreated": DateTime.now(),
  "lastUpdate": DateTime.now(),
  "photographerImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer6_1.png?alt=media&token=60565bee-aa3a-4787-bb46-35af510792f3", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer6_2.png?alt=media&token=8b6da86b-ea2f-485b-ba22-d35b1364b22e", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer6_3.png?alt=media&token=a820daed-6b15-4821-826b-35c8accacf2d", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer6_4.png?alt=media&token=50d4b5b7-c1aa-4794-a970-abd69458cb6b"]
    },
    {
  "photographerId": "7",
  "photographerTitle": "حسن ايمن (hassan_ayman_photograghy)",
  "photographerAddress": "No Address",
  "photographerPhone1": "No Phone",
  "photographerPhone2": "No Phone",
  "photographerPhone3": "No Phone",
  "photographerFacebook": "No Facebook",
  "photographerWhatsApp": "No WhatsApp",
  "photographerDescription": "افضل قاعات الافراح في مصر",
  "photographerPrice": "0.0",
  "photographerLocation": "Other",
  "photographerCategory": "photographer",
  "photographerRating": "5.0",
  "photographerCreated": DateTime.now(),
  "lastUpdate": DateTime.now(),
  "photographerImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer7_1.png?alt=media&token=ff4a82cc-1464-4fdf-b05d-4edfb7230465", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer7_2.png?alt=media&token=282c22b6-89a1-4f84-8800-c1e2049d6f3d", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer7_3.png?alt=media&token=53cc360a-78f0-48d8-9129-b927d7321f93", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer7_4.png?alt=media&token=65c1fcd5-793d-4495-8e19-cc6482433805"]
    },
    {
  "photographerId": "8",
  "photographerTitle": "Veloce Studio",
  "photographerAddress": "No Address",
  "photographerPhone1": "No Phone",
  "photographerPhone2": "No Phone",
  "photographerPhone3": "No Phone",
  "photographerFacebook": "No Facebook",
  "photographerWhatsApp": "No WhatsApp",
  "photographerDescription": "افضل قاعات الافراح في مصر",
  "photographerPrice": "0.0",
  "photographerLocation": "Other",
  "photographerCategory": "photographer",
  "photographerRating": "5.0",
  "photographerCreated": DateTime.now(),
  "lastUpdate": DateTime.now(),
  "photographerImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer8_1.png?alt=media&token=cd09a4ab-4387-4da7-ad53-e9cc6c53ee8f", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer8_2.png?alt=media&token=a4b222a3-6816-4f2a-a520-a054d1ceb58a", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer8_3.png?alt=media&token=c4da49e5-bf75-44f3-9b04-99a2abb33358", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s8_%20photographer_col%2Fphotographer8_4.png?alt=media&token=d130b9fd-d713-4f2d-a46b-08e7efa37b43"]
    }
  ]
};
