Map cafeAndRestaurantData = {
  "data": [
    {
      "cafeAndRestaurantId": "1",
      "cafeAndRestaurantTitle": "كافيه Vasilia Greek Lounge",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant1_1.png?alt=media&token=2c2b23c2-3d7f-48d6-97b1-8521f493b1c5",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant1_2.png?alt=media&token=f324de58-d6e5-4f32-91f9-0e426828e2d3",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant1_3.png?alt=media&token=28e84405-dddb-497f-9378-6fcabf5dbe2a",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant1_4.png?alt=media&token=f4ec69db-93b6-4339-bc74-9bf558216c12"
      ]
    },
    {
      "cafeAndRestaurantId": "2",
      "cafeAndRestaurantTitle": "كافيه Tempo",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant2_1.png?alt=media&token=cdf552b4-7a8f-41f4-97e0-3a22c228ee01",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant2_2.png?alt=media&token=5a5bc5fd-2572-4ab2-b34d-0e5a668ba27f",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant2_3.png?alt=media&token=5d21f333-5d72-4762-ada2-b05062faa338",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant3_1.png?alt=media&token=4a1d7143-ddb1-47bd-8db4-e227021159f4"
      ]
    },
    {
      "cafeAndRestaurantId": "3",
      "cafeAndRestaurantTitle": "كافيه Retro",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant3_2.png?alt=media&token=66bad386-9ef2-4052-a51e-af416c60492d",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant3_3.png?alt=media&token=b2b0e4ce-d230-4534-8e8d-7241a3707dfc",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant3_4.png?alt=media&token=770ce5c6-9549-4a2e-8b01-c2b2caa6e5f9",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant4_1.png?alt=media&token=b51d50a0-cf8a-45a4-8c54-ec1378fa9578"
      ]
    },
    {
      "cafeAndRestaurantId": "4",
      "cafeAndRestaurantTitle": "كافيه Corcovado",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant4_2.png?alt=media&token=e099e19c-89bf-4483-a4b7-9bc89223623c",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant4_3.png?alt=media&token=71b80e81-54e3-4d68-a723-6f725823ca02",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant4_4.png?alt=media&token=66f494ef-e0bd-4ccd-9472-953212c093be",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant5_1.png?alt=media&token=faeceac2-a83a-4974-bd44-6e8f80343088"
      ]
    },
    {
      "cafeAndRestaurantId": "5",
      "cafeAndRestaurantTitle": "كافيه Delavegr",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant5_2.png?alt=media&token=c49c4cd8-e84e-4bde-b9a4-7202688fcbf0",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant5_3.png?alt=media&token=7d728df2-0331-4823-bb1f-ab5613733cc9",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant5_4.png?alt=media&token=8182182e-17d4-400a-9d3e-6b60f047aee5",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant6_1.png?alt=media&token=3993717f-818c-4b5c-be57-39f64343bd21"
      ]
    },
    {
      "cafeAndRestaurantId": "6",
      "cafeAndRestaurantTitle": "كافيه Veto",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant6_2.png?alt=media&token=16a6f019-68c1-4ed0-a003-ba390852e66c",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant6_3.png?alt=media&token=8459d313-982d-46b1-a258-b47811154db3",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant6_4.png?alt=media&token=ce48a60a-3905-4297-b92d-329f1632dd20",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant7_1.png?alt=media&token=5d46f7cc-adaa-4c1f-a3de-d456169af8a3"
      ]
    },
    {
      "cafeAndRestaurantId": "7",
      "cafeAndRestaurantTitle": "كافيه Taverna",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant7_2.png?alt=media&token=abc51db8-25eb-42ab-9994-2739276f560f",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant7_3.png?alt=media&token=9db935ce-12ee-4fd4-9645-6bcde9c8a14a",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant7_4.png?alt=media&token=19bbe17e-8c6c-43dd-a92c-928da27a2c41",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant8_1.png?alt=media&token=0fc2e199-9bce-4b34-bcc8-9b4003bf1f31"
      ]
    },
    {
      "cafeAndRestaurantId": "8",
      "cafeAndRestaurantTitle": "كافيه Lemon",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant8_2.png?alt=media&token=55ec2216-c81f-4f25-94f0-bdcbfd9d0d4c",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant8_3.png?alt=media&token=18d76d6a-bced-4ea6-8172-f8f90d61b2ea",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant8_4.png?alt=media&token=4d2581d2-d4b2-4bc6-804b-e93bf889ad14",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant9_1.png?alt=media&token=5245ea08-d5b7-4cde-8867-34b3397f4171"
      ]
    },
    {
      "cafeAndRestaurantId": "9",
      "cafeAndRestaurantTitle": "كافيه Portofino",
      "cafeAndRestaurantAddress": "No Address",
      "cafeAndRestaurantPhone1": "No Phone",
      "cafeAndRestaurantPhone2": "No Phone",
      "cafeAndRestaurantPhone3": "No Phone",
      "cafeAndRestaurantFacebook": "No Facebook",
      "cafeAndRestaurantWhatsApp": "No WhatsApp",
      "cafeAndRestaurantDescription": "افضل كافيهات في مصر",
      "cafeAndRestaurantPrice": "0.0",
      "cafeAndRestaurantLocation": "Other",
      "cafeAndRestaurantCategory": "cafe_and_restaurant",
      "cafeAndRestaurantRating": "5.0",
      "cafeAndRestaurantCreated": DateTime.now(),
      "lastUpdate": DateTime.now(),
      "cafeAndRestaurantImages": [
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant9_1.png?alt=media&token=5245ea08-d5b7-4cde-8867-34b3397f4171",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant9_2.png?alt=media&token=6b17c333-0fcd-4788-ae8b-5ffa34a2b050",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant9_3.png?alt=media&token=0323b8ed-fced-4f22-9429-6a54a9b44b6f",
        "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s6_cafe_and_restaurant_col%2Fcafe_and_restaurant9_4.png?alt=media&token=5a45d670-3932-4230-ac1d-454933094f23"
      ]
    }
  ]
};
