Map travelData = {
"data": [
    {
    "travelId": "1",
    "travelTitle": "شركة Camp Travel",
    "travelAddress": "No Address",
    "travelPhone1": "No Phone",
    "travelPhone2": "No Phone",
    "travelPhone3": "No Phone",
    "travelFacebook": "No Facebook",
    "travelWhatsApp": "No WhatsApp",
    "travelDescription": "افضل شركات الرحلات في مصر",
    "travelPrice": "0.0",
    "travelLocation": "Other",
    "travelCategory": "travel",
    "travelRating": "5.0",
    "travelCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "travelImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel1_1.png?alt=media&token=f2ad9ab4-51b0-4005-8493-59add8411c47", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel1_2.png?alt=media&token=ed3d6480-8df5-4a87-bbaa-00c71f3479b7", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel1_3.png?alt=media&token=51370863-2f68-42b7-b2da-fd7dcbce5848", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel1_4.png?alt=media&token=f99795db-7c69-4c53-9d68-a3b0ad3c5fd4"]
    },
    {
    "travelId": "2",
    "travelTitle": "شركه سونستا للسياحة Sonesta Tours",
    "travelAddress": "No Address",
    "travelPhone1": "No Phone",
    "travelPhone2": "No Phone",
    "travelPhone3": "No Phone",
    "travelFacebook": "No Facebook",
    "travelWhatsApp": "No WhatsApp",
    "travelDescription": "افضل شركات الرحلات في مصر",
    "travelPrice": "0.0",
    "travelLocation": "Other",
    "travelCategory": "travel",
    "travelRating": "5.0",
    "travelCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "travelImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel2_1.png?alt=media&token=c9b82d53-08cd-4170-9af9-6c45fdf3580c", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel2_2.png?alt=media&token=ace8a2ab-12a6-4786-aebb-f22bc6636330", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel2_3.png?alt=media&token=bee69b96-628f-4cb3-9347-4be5f55706fd", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel2_4.png?alt=media&token=4fb3750e-6840-44cc-bb50-15066ef2348a"]
    },
    {
    "travelId": "3",
    "travelTitle": "شركة DolPhina Travel",
    "travelAddress": "No Address",
    "travelPhone1": "No Phone",
    "travelPhone2": "No Phone",
    "travelPhone3": "No Phone",
    "travelFacebook": "No Facebook",
    "travelWhatsApp": "No WhatsApp",
    "travelDescription": "افضل شركات الرحلات في مصر",
    "travelPrice": "0.0",
    "travelLocation": "Other",
    "travelCategory": "travel",
    "travelRating": "5.0",
    "travelCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "travelImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel3_1.png?alt=media&token=f225fa9c-d49e-478a-87e5-ffb54f541f40", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel3_2.png?alt=media&token=d0787506-2c6e-4d86-a893-a020c14cf571", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel3_3.png?alt=media&token=d13ea446-5d95-4019-9d7b-af860e8eaf58", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel3_4.png?alt=media&token=3ce96c24-82ba-40af-8ed8-0938bf4773a2"]
    },
    {
    "travelId": "4",
    "travelTitle": "شركة رحلتك اون لاين",
    "travelAddress": "No Address",
    "travelPhone1": "No Phone",
    "travelPhone2": "No Phone",
    "travelPhone3": "No Phone",
    "travelFacebook": "No Facebook",
    "travelWhatsApp": "No WhatsApp",
    "travelDescription": "افضل شركات الرحلات في مصر",
    "travelPrice": "0.0",
    "travelLocation": "Other",
    "travelCategory": "travel",
    "travelRating": "5.0",
    "travelCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "travelImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel4_1.png?alt=media&token=023d1ae3-81fe-4a95-b3b9-ba2759aa58ff", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel4_2.png?alt=media&token=1552d4c6-bc76-453e-8cd4-d739b01b903a", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel5_1.png?alt=media&token=8217fdda-861f-4ef4-84cc-315b43df8131", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel5_2.png?alt=media&token=b3d1e73c-9973-475c-8dd1-d0832aae67d1"]
    },
    {
    "travelId": "5",
    "travelTitle": "شركة Cadeau Trips",
    "travelAddress": "No Address",
    "travelPhone1": "No Phone",
    "travelPhone2": "No Phone",
    "travelPhone3": "No Phone",
    "travelFacebook": "No Facebook",
    "travelWhatsApp": "No WhatsApp",
    "travelDescription": "افضل شركات الرحلات في مصر",
    "travelPrice": "0.0",
    "travelLocation": "Other",
    "travelCategory": "travel",
    "travelRating": "5.0",
    "travelCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "travelImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel5_1.png?alt=media&token=8217fdda-861f-4ef4-84cc-315b43df8131","https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel5_2.png?alt=media&token=b3d1e73c-9973-475c-8dd1-d0832aae67d1","https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel5_3.png?alt=media&token=fef22b68-d13c-42e7-b26d-302cc133def7","https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s7_travel_col%2Ftravel5_4.png?alt=media&token=b1acbbd1-451b-48f9-98aa-1cdd63bac53b"]
    }
  ]
};
