Map makeupArtistData = {
"data": [
    {
    "makeupArtistId": "1",
    "makeupArtistTitle": "ندي درويش - makeup_by_nada_darwish",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "01102545725",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist1_1.png?alt=media&token=d681c5ad-fb5d-483d-bd93-4d60e473dd95", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist1_2.png?alt=media&token=30c6387e-690a-46e9-8503-ff2fb3cce481", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist1_3.png?alt=media&token=1f8fd3db-24fb-41c8-8070-178cc2eef90f", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist1_4.png?alt=media&token=3181c689-56ec-49da-8134-5bb7c3334c01"]
    },
    {
    "makeupArtistId": "2",
    "makeupArtistTitle": "يمني يوسف youmnayoussefmakeupartist",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "01278571978",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist2_1.png?alt=media&token=c7d9a1ca-4e20-4841-96dc-05b1e1c458cd", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist2_2.png?alt=media&token=f36ec7c1-7628-4803-9211-c3937c0abd10", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist2_3.png?alt=media&token=9c0099c9-1d95-4de6-b784-7992c2ad760c", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist2_4.png?alt=media&token=dcba2930-1233-4cf9-a183-bc8f0edf616d"]
    },
    {
    "makeupArtistId": "3",
    "makeupArtistTitle": "هبه مرشدي makeup_with_hebamorshdy",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "0115673374",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist3_1.png?alt=media&token=f9bb58b5-8743-4117-9d93-db29af0af49a", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist3_2.png?alt=media&token=042d00f4-414f-4278-8272-2a4fcd4a9c21", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist3_3.png?alt=media&token=54460c1b-32d4-4a16-9c2e-bd7a3939a028", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist3_4.png?alt=media&token=c4b89db5-6e89-4773-ae65-e6b7540cbb74"]
    },
    {
    "makeupArtistId": "4",
    "makeupArtistTitle": "ندي عبده Nada abdo Makeup artistt ",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "01016384678",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist4_1.png?alt=media&token=70ba9a01-2875-4c8a-a943-0eac76bd2e6e", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist4_2.png?alt=media&token=69aa8116-8b09-4bbe-9177-4d79cb0c2ffc", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist4_3.png?alt=media&token=799343e3-4442-454c-aae2-c86f15976da6", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist4_4.png?alt=media&token=7b0a88fe-81dd-4787-978a-06cfac6e566f"]
    },
    {
    "makeupArtistId": "5",
    "makeupArtistTitle": "شيرين يحي makeup_with_sherry_yehia",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "01274011064",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist5_1.png?alt=media&token=58a35d62-50b4-4583-908b-0a0cb8ee7fb8", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist5_2.png?alt=media&token=edc376e6-67cb-4fac-8d63-3ff25048c350", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist5_3.png?alt=media&token=c31e7d73-14e5-4788-8494-161b50155166", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist5_4.png?alt=media&token=d62bd0d1-1523-4fac-b341-f42b6ab0730c"]
    },
    {
    "makeupArtistId": "6",
    "makeupArtistTitle": "لمسه Lamsa make up artist",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "01023492471",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist6_1.png?alt=media&token=772fe402-d8f1-4e95-a48d-6eea44407bdf", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist6_2.png?alt=media&token=601fd4ab-2132-4baa-9e8d-a773af65866e", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist6_3.png?alt=media&token=054698bf-3716-431e-beb5-6088d93cc515", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist6_4.png?alt=media&token=77c2701d-eb0d-4736-8a0c-49d3a8ff5cc8"]
    },
    {
    "makeupArtistId": "7",
    "makeupArtistTitle": "اسماء صدقي Asmaa sedky make up Artist",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "01224668971",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist7_1.png?alt=media&token=d119cdc7-25f1-4799-8285-44c0be55b681", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist7_2.png?alt=media&token=22ae2e65-9081-4c0c-9084-2e37949f3b65", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist7_3.png?alt=media&token=fda3c463-dfc7-49ee-ac61-d07bc1095e3a", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist7_4.png?alt=media&token=f17deeff-3cfd-4f2e-b7ad-db131dc8afec"]
    },
    {
    "makeupArtistId": "8",
    "makeupArtistTitle": "خلود خالد khloud_khaled_makeup_artist",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "01203531514",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist8_1.png?alt=media&token=2d1f91b7-9645-4b1f-a6f8-a1db8c2e7a3a", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist8_2.png?alt=media&token=ddc3aafc-388b-46b1-820b-882fc5a6bb7e", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist8_3.png?alt=media&token=c044854f-a5a7-4701-b85c-2b92a8570619", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist8_4.png?alt=media&token=01cc8dad-597c-4122-93d3-5fde141346f2"]
    },
    {
    "makeupArtistId": "9",
    "makeupArtistTitle": "منه عثمان makeup_by_mennamohamed",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "No Phone",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist9_1.png?alt=media&token=b1c7920e-5f4e-4bc8-834c-79fe169545bf", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist9_2.png?alt=media&token=13058e48-c77f-4da6-bcce-6d96eece93a3", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist9_3.png?alt=media&token=b5e4c6d3-446e-4c5d-9bb3-ccbc587e03a5", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist9_4.png?alt=media&token=5641a421-bcd9-443b-93dc-939e9dad6f33"]
    },
    {
    "makeupArtistId": "10",
    "makeupArtistTitle": "ماجي magy_makeupartist",
    "makeupArtistAddress": "No Address",
    "makeupArtistPhone1": "No Phone",
    "makeupArtistPhone2": "No Phone",
    "makeupArtistPhone3": "No Phone",
    "makeupArtistFacebook": "No Facebook",
    "makeupArtistWhatsApp": "No WhatsApp",
    "makeupArtistDescription": "افضل ميكب ارتست في مصر",
    "makeupArtistPrice": "0.0",
    "makeupArtistLocation": "Other",
    "makeupArtistCategory": "makeup_artist",
    "makeupArtistRating": "5.0",
    "makeupArtistCreated": DateTime.now(),
    "lastUpdate": DateTime.now(),
    "makeupArtistImages": ["https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist10_1.png?alt=media&token=7675cd31-0340-474b-bba4-1c1bde9ec988", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist10_2.png?alt=media&token=7d84d3f4-e39d-4c0e-9a7b-78f40fae6e2d", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist10_3.png?alt=media&token=0e05c1e8-15e9-441e-9ea6-548cc5cb74b1", "https://firebasestorage.googleapis.com/v0/b/wahg-4.appspot.com/o/s3_makeup_artist_col%2Fmakeup_artist10_4.png?alt=media&token=d1f47a52-d26c-447e-8660-cc2f9e89a565"]
    }
  ]
};
