name: wahg_v1
description: "This is Wahg Mobile App - It's a wedding app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  ###### ORGANIZED ##########

  #FIREBASE
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.15
  cloud_firestore: ^4.14.0
  flutter_local_notifications: ^16.3.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.6

  #STATE MANAGEMENT
  get: ^4.6.5
  get_it: ^7.6.6
  mobx: ^2.3.0+1
  flutter_mobx: ^2.0.6+4
  #  bloc: ^8.1.2
  flutter_bloc: ^8.1.3


  #DATA
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.18.0

  #DEVICE

  #LOCALIZATION
#  easy_localization: ^3.0.3
  flutter_localizations:
    sdk: flutter

  #NETWORK
  url_launcher: ^6.2.2
  data_connection_checker_nulls: ^0.0.2
  connectivity_plus: ^5.0.2
  html: ^0.15.4

  #UTILITES
  getwidget: ^4.0.0
  nb_utils: ^6.1.0
  restart_app: ^1.2.1

  #UI
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  lottie: ^2.3.2
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  flutter_slidable: 0.6.0
  smooth_page_indicator: 1.1.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  eva_icons_flutter: ^3.1.0






  ##################


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7+3
  build_runner: ^2.2.1
    #flutter packages pub run build_runner build --delete-conflicting-outputs



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Comforter
      fonts:
        - asset: assets/fonts/ComforterRegular.ttf
          weight: 400

    - family: Kantumruy
      fonts:
        - asset: assets/fonts/Kantumruy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kantumruy-Regular.ttf
          weight: 400


    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
          weight: 400

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400


