// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHzE7VNZVeU5NUOSU81mTw-MZWIsRLTTo',
    appId: '1:710415558330:web:286f19c67393993e8dc483',
    messagingSenderId: '710415558330',
    projectId: 'wahg-4',
    authDomain: 'wahg-4.firebaseapp.com',
    storageBucket: 'wahg-4.appspot.com',
    measurementId: 'G-3PM0Q7KDPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASMJRwEjyw6vTUXjgX7nVDkfUCO9knrhA',
    appId: '1:710415558330:android:025d5140548567598dc483',
    messagingSenderId: '710415558330',
    projectId: 'wahg-4',
    storageBucket: 'wahg-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YMrsWd82wduFH3GVMnzpynl3sGdcYVE',
    appId: '1:710415558330:ios:896647b93765e6128dc483',
    messagingSenderId: '710415558330',
    projectId: 'wahg-4',
    storageBucket: 'wahg-4.appspot.com',
    iosBundleId: 'com.example.wahgV1',
  );
}
